#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const pluginDir = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const defaultInput = '/home/mikael/Documents/projects/kim/OpenGL-WebAssembly/web/single.html';
const defaultOutput = path.join(pluginDir, 'ViewerSingleHtml.generated.as');

const inputPath = process.argv[2] ? path.resolve(process.argv[2]) : defaultInput;
const outputPath = process.argv[3] ? path.resolve(process.argv[3]) : defaultOutput;
const chunkSize = 2000;

function escapeForAngelString(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t');
}

if (!fs.existsSync(inputPath)) {
  console.error(`Input file not found: ${inputPath}`);
  process.exit(1);
}

const html = fs.readFileSync(inputPath, 'utf8');
const chunks = [];
for (let i = 0; i < html.length; i += chunkSize) {
  chunks.push(html.slice(i, i + chunkSize));
}

let out = '';
out += '// Auto-generated by scripts/generate_viewer_single_embed.mjs\n';
out += `// Source: ${inputPath}\n`;
out += '// Do not edit by hand. Re-run generator after modifying single.html.\n\n';
out += 'string GetEmbeddedViewerSingleHtml()\n';
out += '{\n';
out += '    string html = "";\n';
for (const chunk of chunks) {
  out += `    html += "${escapeForAngelString(chunk)}";\n`;
}
out += '    return html;\n';
out += '}\n';

fs.writeFileSync(outputPath, out, 'utf8');
console.log(`Generated ${outputPath}`);
console.log(`Chunks: ${chunks.length}, input chars: ${html.length}`);
